schema-version: v3
kind: plugin
metadata:
  name: java-web
  display-name: java-web
  description: Plugin para inicializar um Projeto de Automação Java Web.
  version: 0.0.2
spec:
  type: app
  compatibility:
    - java
  docs:
    en-us: docs/en-us/docs.md
    pt-br: docs/pt-br/docs.md
  single-use: False
  repository: https://github.com/rosedias/pluginstack-javaweb.git
  technologies: 
    - "java"
  inputs:
    - label: Nome do Projeto
      name: Nome-do-Projeto
      type: text
      required: true
      default: java-app
      help: 'Informe o nome do projeto Java'
    - label: Versao Java
      name: version-java
      type: select
      items:
        - "8"
        - "11"
        - "17"
        - "22"
      default: "22"
      required: true
      help: 'Selecione a versão do Java'
