schema-version: v3
kind: plugin
metadata:
  name: java-web
  display-name: java-web
  description: Plugin para inicializar um Projeto de Automação Java Web.
  version: 0.0.1
spec:
  type: app
  compatibility:
    - python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  repository: https://github.com/rosedias/pluginstack-javaweb.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
  stk-projects-only: false
  inputs:
    - label: Type the name of your resource
      name: resource
      type: text
      required: true
      default: Client
      pattern: '([A-Z][a-z]+)+'
      help: 'Inform your resource name (e.g.: Client)'
    - label: Choose the http method of the new endpoint
      name: method
      type: select
      items:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      default: GET
      required: true
      help: 'Inform the method of the endpoint (e.g.: post or delete)'
