schema-version: v3
kind: plugin
metadata:
  name: java-web
  display-name: java-web
  description: Plugin para inicializar um Projeto de Automação Java Web.
  version: 0.0.1
spec:
  type: app
  compatibility:
    - python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  repository: https://github.com/rosedias/pluginstack-javaweb.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Java
  inputs:
    - label: Nome do Projeto
      name: project_name
      type: text
      required: true
      default: java-app
      help: 'Informe o nome do projeto Java'
    - label: Versao Java
      name: version_java
      type: select
      items:
        - 8
        - 11
        - 17
        - 22
      default: 22
      required: true
      help: 'Selecione a versão do Java'
